services:
    database:
        image: mariadb:11.4-ubi
        environment:
            - MYSQL_DATABASE=${DATABASE_NAME}
            - MYSQL_USER=${DATABASE_USER}
            - MYSQL_PASSWORD=${DATABASE_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
        volumes:
            - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:delegated
            - ./database/data:/var/lib/mysql:delegated
        ports:
            - "33060:3306"

    php-fpm:
        build:
            context: ./php-fpm
#        image: k0pernikus/php-dev-base
        container_name: base
        hostname: php
        depends_on:
            - database
        environment:
            - APP_ENV=${APP_ENV}
            - APP_SECRET=${APP_SECRET}
            - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@database:3306/${DATABASE_NAME}?serverVersion=mariadb-11.4.0B&charset=utf8mb4
        volumes:
            - ./php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:delegated
            - ./php-fpm/path.sh:/etc/profile.d/path.sh
            - ./php-fpm/ssh:/etc/ssh
        ports:
            - "33022:22"

    nginx:
        build:
            context: ./nginx
        volumes:
            - ../app:/var/www:cached
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:delegated
            - ./nginx/sites/:/etc/nginx/sites-available:delegated
            - ./nginx/conf.d/:/etc/nginx/conf.d:delegated
            - ./logs:/var/log:delegated
        depends_on:
            - php-fpm
        ports:
            - "8080:80"
            - "443:443"
